### ISSUE TITLE
Issues installing can amyone help

### ISSUE THREAD

**Issue by tommo5600** [slightlynybbled/tk_tools#26]
Might be a simle fix but i've only just stated to use Python/ Pi

pi@raspberrypi:~ $ sudo pip install https://github.com/slightlynybbled/tk_tools.git
Collecting https://github.com/slightlynybbled/tk_tools.git
  Downloading https://github.com/slightlynybbled/tk_tools.git
     / 81kB 461kB/s
  Cannot unpack file /tmp/pip-RVSs3O-unpack/tk_tools.git (downloaded from /tmp/pip-II44TN-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-II44TN-build

**Comment by slightlynybbled** [comment]
Welcome to python!

Try simply `pip3 install tk-tools`.  There is a repository called the [Python Package Index](http://www.pypi.org) which stores the packages which is super easy to use.  The `pip3` should get it from there.  Note that I'm stating `pip3` instead of `pip` because in many linux distributions, `pip` will get you python 2 and not python 3.

If you wish to install from the repository, then you will have to `git clone </repository/url>` and run `python3 setup.py install` from inside the directory.  The `setup.py` is really intended for developers, thus, there are more installs required to place the development tools in-place.

I haven't worked with recent raspberry pi distributions, but there was a time which you had to also run `sudo apt-get install python3-tk` to get access to tk.  Good luck!

**Comment by tommo5600** [comment]
solved it thank you so much! forgive my poor grammar and spelling, in a rush using a poor keyboard!
